const places = [
    {"id": "1","image": "https://media.cntraveler.com/photos/55c8be0bd36458796e4ca38a/master/w_1200,c_limit/london-eye-2-cr-getty.jpg?mbid=social_retweet","title": "London Eye","description": "One of the world's largest observation wheels offering stunning views of London."},
    {"id": "2","image": "https://tse2.mm.bing.net/th?id=OIP.0AMqPCw8-B01sqXw16VARAHaEp&pid=ImgDet&rs=1","title": "Tower of London","description": "Historic castle on the north bank of the River Thames."},
    {"id": "3","image": "https://tse3.mm.bing.net/th?id=OIP.e5aBzFY6EVWQhk4RdQW-TwHaE8&pid=ImgDet&w=1600&h=1067&rs=1","title": "Stonehenge","description": "Prehistoric monument in Wiltshire, England."},
    {"id": "4","image": "https://tse2.mm.bing.net/th?id=OIP.QsOiXp3_SOCasdclJ1YMIQHaE8&pid=ImgDet&rs=1","title": "Roman Baths","description": "A well-preserved Roman site for public bathing."},
    {"id": "5","image": "http://example.com/windsor_castle.jpg","title": "Windsor Castle","description": "A royal residence at Windsor in the English county of Berkshire."},
    {"id": "6","image": "http://example.com/big_ben.jpg","title": "Big Ben","description": "The nickname for the Great Bell of the clock at the north end of the Palace of Westminster."},
    {"id": "7","image": "http://example.com/edinburgh_castle.jpg","title": "Edinburgh Castle","description": "Historic fortress which dominates the skyline of Edinburgh."},
    {"id": "8","image": "http://example.com/loch_ness.jpg","title": "Loch Ness","description": "A large, deep, freshwater loch in the Scottish Highlands."},
    {"id": "9","image": "http://example.com/skye.jpg","title": "Isle of Skye","description": "Known for its rugged landscapes, picturesque fishing villages and medieval castles."},
    {"id": "10","image": "http://example.com/snowdonia.jpg","title": "Snowdonia National Park","description": "Home to Snowdon, the highest mountain in Wales."},
    {"id": "11","image": "http://example.com/cardiff_castle.jpg","title": "Cardiff Castle","description": "A medieval castle and Victorian Gothic revival mansion."},
    {"id": "12","image": "http://example.com/giants_causeway.jpg","title": "Giant's Causeway","description": "An area of about 40,000 interlocking basalt columns."},
    {"id": "13","image": "http://example.com/titanic_belfast.jpg","title": "Titanic Belfast","description": "Museum on the site of the former Harland & Wolff shipyard."},
    {"id": "14","image": "http://example.com/ulster_museum.jpg","title": "Ulster Museum","description": "Northern Ireland's treasure house of past and present."},
    {"id": "15","image": "http://example.com/derry_walls.jpg","title": "Derry's Walls","description": "One of the best examples of a walled city in Europe."},
    {"id": "16","image": "http://example.com/dark_hedges.jpg","title": "Dark Hedges","description": "A beautiful avenue of beech trees."},
    {"id": "17","image": "http://example.com/brecon_beacons.jpg","title": "Brecon Beacons National Park","description": "Known for its remote reservoirs, waterfalls and mountain ranges."},
    {"id": "18","image": "http://example.com/caernarfon_castle.jpg","title": "Caernarfon Castle","description": "A medieval fortress in Caernarfon, Gwynedd."},
    {"id": "19","image": "http://example.com/stirling_castle.jpg","title": "Stirling Castle","description": "One of the largest and most important castles in Scotland."},
    {"id": "20","image": "http://example.com/glencoe.jpg","title": "Glencoe","description": "Famous for its dramatic landscapes, it is a part of the designated National Scenic Area."},
    {"id": "21","image": "http://example.com/ben_nevis.jpg","title": "Ben Nevis","description": "The highest mountain in the British Isles."},
    {"id": "22","image": "http://example.com/royal_mile.jpg","title": "The Royal Mile","description": "The main artery of the Old Town of Edinburgh."},
    {"id": "23","image": "http://example.com/stratford.jpg","title": "Stratford-upon-Avon","description": "A market town with more than 800 years of history."},
    {"id": "24","image": "http://example.com/lake_district.jpg","title": "Lake District","description": "A popular holiday destination, it's known for its glacial ribbon lakes."},
    {"id": "25","image": "http://example.com/british_museum.jpg","title": "British Museum","description": "A public institution dedicated to human history, art and culture."},
    {"id": "26","image": "http://example.com/york_minster.jpg","title": "York Minster","description": "One of the largest of its kind in Northern Europe."},
    {"id": "27","image": "http://example.com/white_cliffs.jpg","title": "White Cliffs of Dover","description": "Famous for their white chalk face, a symbol of home and war time defense."},
    {"id": "28","image": "http://example.com/jurassic_coast.jpg","title": "Jurassic Coast","description": "England’s first natural World Heritage Site, covers 95 miles of coastline."},
    {"id": "29","image": "http://example.com/cambridge_university.jpg","title": "University of Cambridge","description": "A collegiate research university in Cambridge, United Kingdom."},
    {"id": "30","image": "http://example.com/shakespeares_birthplace.jpg","title": "Shakespeare’s Birthplace","description": "A restored 16th-century half-timbered house."},
    {"id": "31","image": "http://example.com/scottish_highlands.jpg","title": "Scottish Highlands","description": "Renowned for its stunning scenery, it's a wilderness of sunlit peaks."},
    {"id": "32","image": "http://example.com/glasgow_science_center.jpg","title": "Glasgow Science Centre","description": "A visitor attraction located in the Clyde Waterfront Regeneration area."},
    {"id": "33","image": "http://example.com/balmoral_castle.jpg","title": "Balmoral Castle","description": "A large estate house in Royal Deeside, Aberdeenshire."},
    {"id": "34","image": "http://example.com/st_andrews.jpg","title": "St Andrews","description": "A town on the east coast of Fife in Scotland."},
    {"id": "35","image": "http://example.com/aberdeen.jpg","title": "City of Aberdeen","description": "Scotland's third most populous city, known as 'The Granite City'."},
    {"id": "36","image": "http://example.com/saint_davids.jpg","title": "St Davids","description": "A city and a community in Pembrokeshire."},
    {"id": "37","image": "http://example.com/llandudno.jpg","title": "Llandudno","description": "A seaside resort, town and community in Conwy County Borough, Wales."},
    {"id": "38","image": "http://example.com/swansea.jpg","title": "City of Swansea","description": "Known for its vibrant nightlife and sprawling marina."},
    {"id": "39","image": "http://example.com/anglesey.jpg","title": "Anglesey","description": "An island off the northwest coast of Wales."},
    {"id": "40","image": "http://example.com/hay_on_wye.jpg","title": "Hay-on-Wye","description": "The 'town of books', with over twenty bookshops."},
    {"id": "41","image": "http://example.com/dunluce_castle.jpg","title": "Dunluce Castle","description": "The ruins of a medieval castle in Northern Ireland."},
    {"id": "42","image": "http://example.com/belfast_castle.jpg","title": "Belfast Castle","description": "A baronial style building located in Belfast."},
    {"id": "43","image": "http://example.com/mourne_mountains.jpg","title": "Mourne Mountains","description": "Designated as an area of outstanding natural beauty."},
    {"id": "44","image": "http://example.com/marble_arch_caves.jpg","title": "Marble Arch Caves","description": "One of Europe's finest show caves."},
    {"id": "45","image": "http://example.com/bushmills_distillery.jpg","title": "Bushmills Distillery","description": "Home of the famous Irish whiskey."},
    {"id": "46","image": "http://example.com/lough_neagh.jpg","title": "Lough Neagh","description": "The largest lake by area in the British Isles."},
    {"id": "47","image": "http://example.com/cavehill.jpg","title": "Cave Hill","description": "Most famous for its striking basaltic columns, it's also known as Napoleon's Nose."},
    {"id": "48","image": "http://example.com/st_davids_cathedral.jpg","title": "St Davids Cathedral","description": "The cathedral is the final resting place of Saint David."},
    {"id": "49","image": "http://example.com/millennium_stadium.jpg","title": "Millennium Stadium","description": "Also known as the Principality Stadium, a multi-purpose venue."},
    {"id": "50","image": "http://example.com/pembrokeshire_coast.jpg","title": "Pembrokeshire Coast National Park","description": "Known for its stunning coastline and diverse wildlife."},
    {"id": "51","image": "http://example.com/portmeirion.jpg","title": "Portmeirion","description": "A unique and quirky coastal village."},
    {"id": "52","image": "http://example.com/bodnant_garden.jpg","title": "Bodnant Garden","description": "One of the most beautiful gardens in the UK."},
    {"id": "53","image": "http://example.com/tintern_abbey.jpg","title": "Tintern Abbey","description": "The ruins of an abbey, founded by Cistercian monks."},
    {"id": "54","image": "http://example.com/welsh_mountains.jpg","title": "The Welsh Mountains","description": "Known for their stunning beauty and outdoor activities."},
    {"id": "55","image": "http://example.com/carrick_a_rede.jpg","title": "Carrick-a-Rede Rope Bridge","description": "A famous rope bridge near Ballintoy."},
    {"id": "56","image": "http://example.com/armagh.jpg","title": "City of Armagh","description": "Known for its Georgian architecture and tree-lined Mall."},
    {"id": "57","image": "http://example.com/st_patricks_cathedral.jpg","title": "St Patrick's Cathedral","description": "One of the oldest Christian sites in Ireland."},
    {"id": "58","image": "http://example.com/hadrians_wall.jpg","title": "Hadrian's Wall","description": "Roman defensive fortification in Northern England."},
    {"id": "59","image": "http://example.com/chester_zoo.jpg","title": "Chester Zoo","description": "One of the UK's largest zoos at 51 hectares."},
    {"id": "60","image": "http://example.com/warwick_castle.jpg","title": "Warwick Castle","description": "A medieval castle developed from a wooden fort, originally built by William the Conqueror."}
]

module.exports = places;

